# render.yaml (最终确认版)

services:
  - type: web
    name: trading-system-v7
    runtime: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/main.py"
    healthCheck:
      path: /health
      initialDelaySeconds: 120
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13"
      - key: PORT
        fromService:
          type: web
          name: trading-system-v7
          property: port