services:
  - type: web
    name: trading-systemV-v7
    runtime: docker
    dockerfilePath: ./Dockerfile
    
    # 新增的预启动命令
    preStartCommand: |
      mkdir -p /var/data
      chmod 777 /var/data
      echo "✅ 数据库目录权限已设置"
    
    healthCheck:
      path: /health
      initialDelaySeconds: 120
      
    envVars:
      - key: PORT
        value: 8000
      - key: RENDER
        value: "true"  # 标记Render环境
      - key: EXCHANGE_MAX_RETRIES
        value: "3"
      - key: EXCHANGE_RETRY_DELAY
        value: "5"
