services:
  - type: web
    name: trading-system
    env: python
    python:
      version: "3.10.13"
    buildCommand: ./render-build.sh
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
