services:
  - type: web
    name: trading-systemV7.0# 确保这个名字和您在 Render 网站上看到的服务名一致

    runtime: python
    plan: starter
    
    # 直接在这里定义构建和启动命令
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/main.py"
    
    # 关键的健康检查配置
    healthCheck:
      path: /health
      initialDelaySeconds: 120
      
    # 环境变量 (这里的 PYTHON_VERSION 是解决问题的关键！)
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13" # 强制 Render 使用这个稳定版本
      - key: PORT
        fromService:
          type: web
          name: trading-systemV7.0
          property: port