services:
  - type: web
    name: trading-systemV-v7
    runtime: docker
    dockerfilePath: ./Dockerfile
    
    # 修改数据目录路径以匹配Dockerfile
    preStartCommand: |
      mkdir -p /app/data
      chmod 750 /app/data
      echo "✅ 数据目录权限已设置"
    
    healthCheck:
      path: /health
      initialDelaySeconds: 120
      
    envVars:
      - key: PORT
        value: 8000
      - key: RENDER
        value: "true"
      - key: EXCHANGE_MAX_RETRIES
        value: "3"
      - key: EXCHANGE_RETRY_DELAY
        value: "5"
