services:
  - type: web
    name: trading-systemV7.0
    runtime: python
    plan: starter 
    buildCommand: "./render-build.sh"
    startCommand: "./start.sh"
    healthCheck:
      path: /health               
      initialDelaySeconds: 120    
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13" 
      - key: PORT
        fromService:
          type: web
          name: trading-systemV7.0
          property: port
